import { Meeting, WeekType } from '../types';

export const getDefaultMeetings = (): Meeting[] => {
  return [
    {
      id: 1,
      name: 'Daily Stand-up',
      categoryId: 'starfox',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
      startTime: '10:00 AM',
      endTime: '10:30 AM',
      weekType: WeekType.Both,
      requiresAttendance: 'All Starfox members',
      notes: 'Daily collaboration and blockers discussion',
      assignedTo: '',
    },
    {
      id: 2,
      name: 'Developer Sync',
      categoryId: 'starfox',
      days: ['Monday'],
      startTime: '2:00 PM',
      endTime: '3:00 PM',
      weekType: WeekType.Both,
      requiresAttendance: 'MBL ART devs, testers + 1 RDS rep',
      notes: 'Weekly technical sync',
      assignedTo: '',
    },
    {
      id: 3,
      name: 'Lead Sync',
      categoryId: 'starfox',
      days: ['Friday'],
      startTime: '12:00 PM',
      endTime: '1:00 PM',
      weekType: WeekType.Both,
      requiresAttendance: 'Team leads from RDS and MBL ART',
      notes: 'Weekly leadership alignment',
      assignedTo: '',
    },
    {
      id: 4,
      name: 'Iteration Retro and Planning',
      categoryId: 'starfox',
      days: ['Tuesday'],
      startTime: '4:00 PM',
      endTime: '5:00 PM',
      weekType: WeekType.A,
      requiresAttendance: 'All Starfox members',
      notes: 'Biweekly retrospective and planning',
      assignedTo: '',
    },
    {
      id: 5,
      name: 'Design Backlog Refinement',
      categoryId: 'starfox',
      days: ['Tuesday'],
      startTime: '4:05 PM',
      endTime: '5:00 PM',
      weekType: WeekType.B,
      requiresAttendance: 'RDS designers + 1 dev rep',
      notes: 'Biweekly design work refinement',
      assignedTo: '',
    },
    {
      id: 7,
      name: 'RDS Daily Stand-up',
      categoryId: 'rds',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      startTime: '12:00 PM',
      endTime: '12:30 PM',
      weekType: WeekType.Both,
      requiresAttendance: 'RDS designers',
      notes: 'Daily RDS team sync',
      assignedTo: '',
    },
  ];
};

